Message:
  Success:
    Deposit: '&a经验保存成功'
    Withdraw: '成功取出经验'
  Failure:
    NotEnoughExp: '经验不足'
    NumberFormatError: '输入格式错误'
    MissingArgument: '&c缺少参数！使用 /expbank help 查看帮助'
    InvalidCommand: '&c无效指令！使用 /expbank help 查看帮助'
